name: Pre Merge Checks
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - '*'
  workflow_dispatch:
    branches:
      - '*'

jobs:
  test:
    runs-on: [ubuntu-latest]

    steps:
    - name: Cancel Previous Runs
      if: github.event_name == 'pull_request'
      uses: styfle/cancel-workflow-action@0.10.0
      with:
        access_token: ${{ github.token }}

    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Cache Gradle Folders
      uses: gradle/gradle-build-action@v2

    - name: Run all the tests
      run: ./gradlew test

    - name: Stop Gradle
      run: ./gradlew --stop

  detekt:
    runs-on: [ubuntu-latest]

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Cache Gradle Folders
      uses: gradle/gradle-build-action@v2

    - name: Run detekt
      run: ./gradlew detekt

    - name: Stop Gradle
      run: ./gradlew --stop

  lint:
    runs-on: [ubuntu-latest]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Cache Gradle Folders
        uses: gradle/gradle-build-action@v2

      - name: Run lint
        run: ./gradlew lint

      - name: Stop Gradle
        run: ./gradlew --stop

  ktlint:
    runs-on: [ubuntu-latest]

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Cache Gradle Folders
      uses: gradle/gradle-build-action@v2

    - name: Run ktlint
      run: ./gradlew ktlintCheck

    - name: Stop Gradle
      run: ./gradlew --stop

  api-check:
    runs-on: [ubuntu-latest]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Cache Gradle Folders
        uses: gradle/gradle-build-action@v2

      - name: Run apiCheck
        run: ./gradlew apiCheck

      - name: Stop Gradle
        run: ./gradlew --stop

  publish-artifact:
    runs-on: [ubuntu-latest]

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Cache Gradle Folders
      uses: gradle/gradle-build-action@v2

    - name: Publish to Maven Local
      run: ./gradlew publishToMavenLocal
      env:
        ORG_GRADLE_PROJECT_SIGNING_KEY: ${{ secrets.ORG_GRADLE_PROJECT_SIGNING_KEY }}
        ORG_GRADLE_PROJECT_SIGNING_PWD: ${{ secrets.ORG_GRADLE_PROJECT_SIGNING_PWD }}

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: 'chucker-local-artifacts'
        path: '~/.m2/repository/'

    - name: Stop Gradle
      run: ./gradlew --stop
